name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest, ubuntu-24.04]
        dotnet: [10.0.x]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore tools
        run: dotnet tool restore

      - name: Run Build
        run: dotnet build -c Debug

      - name: Run Tests
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          CORES=$(nproc)
          WORKERS=$(( CORES / 2 ))
          if [ "$WORKERS" -lt 1 ]; then
            WORKERS=1
          fi

          echo "Total cores: $CORES, running tests with $WORKERS workers"
          dotnet test --no-build -- NUnit.NumberOfTestWorkers=$WORKERS

      - name: Run Tests
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          $cores = [int]$env:NUMBER_OF_PROCESSORS
          $workers = [Math]::Max(1, [Math]::Floor($cores / 2))

          Write-Host "Total cores: $cores, running tests with $workers workers"
          dotnet test --no-build -- NUnit.NumberOfTestWorkers=$workers

      - name: Run Fantomas check
        run: dotnet fantomas --check .

      - name: Check dotnet pack works for Release config
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          dotnet build -c Release
          dotnet pack -c Release -o release --no-build
        working-directory: src/CSharpLanguageServer
